(async function(){
 const id=new URLSearchParams(location.search).get("id"), m=document.getElementById("message");
 if(!id||!window.birthPortalAuth?.ready){m.textContent="Invalid certificate.";return}
 const gate=await window.birthPortalAuth.requireAdmin(); if(!gate)return; const db=window.birthPortalAuth.client;
 const {data:c,error}=await db.from("certificates").select("*,states(name_en,code),districts(name_en),local_bodies(*)").eq("id",id).single();
 if(error){m.textContent=error.message;return}
 const set=(x,v)=>{const e=document.getElementById(x);if(e)e.textContent=(v??"")||"—"};
 const ef=c.extra_fields||{}, b=c.local_bodies||{};
 const lang=window.birthPortalStateLanguage?.STATE_LANGUAGE?.[c.states?.code]||"en";
 const T=window.birthPortalStateLanguage?.T||{}, d=Object.assign({},T.en||{},T[lang]||{});
 const birth=c.certificate_type==="birth";
 set("serial",c.certificate_number?.split("-").pop());
 set("stateHeading",(c.states?.name_en||"STATE / UNION TERRITORY").toUpperCase());
 set("stateLocal",d.stateName||"");
 set("department",(b.department_en||"DEPARTMENT OF HEALTH").toUpperCase());
 set("bodyHeading",(b.name_en||"LOCAL REGISTRATION AUTHORITY").toUpperCase()); set("bodyLocal",b.name_local);
 set("formNo",birth?"FORM 5":"DEATH CERTIFICATE"); set("formNoLocal",birth?"प्रपत्र-5":"");
 set("title",birth?"BIRTH CERTIFICATE":"DEATH CERTIFICATE");
 set("titleLocal",birth?(d.birthTitle||""):(d.deathTitle||""));
 set("legalEn",birth?"CERTIFICATE OF BIRTH — DETAILS RECORDED IN THE PORTAL.":"CERTIFICATE OF DEATH — DETAILS RECORDED IN THE PORTAL.");
 set("legalLocal","");
 set("name",c.person_name);set("nameLocal",ef.person_name_local);set("gender",c.gender);set("aadhaar",c.aadhaar_number);
 set("date",c.date_of_event);set("place",c.place_of_event);set("placeLocal",ef.place_of_event_local);
 set("mother",c.mother_name);set("motherLocal",ef.mother_name_local);set("father",c.father_name);set("fatherLocal",ef.father_name_local);
 set("motherAadhaar",c.mother_aadhaar);set("fatherAadhaar",c.father_aadhaar);
 set("addressEvent",c.address_at_event);set("addressEventLocal",ef.address_at_event_local);
 set("permanentAddress",c.permanent_address);set("permanentAddressLocal",ef.permanent_address_local);
 set("reg",c.registration_number);set("regDate",c.registration_date);set("number",c.certificate_number);set("issue",c.issue_date);
 set("remarks",c.remarks);set("remarksLocal",ef.remarks_local);set("updated",c.updated_at?new Date(c.updated_at).toLocaleString():"");
 set("dateLabel",birth?"DATE OF BIRTH":"DATE OF DEATH");set("placeLabel",birth?"PLACE OF BIRTH":"PLACE OF DEATH");
 set("addressEventLabel",birth?"ADDRESS OF PARENTS AT THE TIME OF BIRTH":"ADDRESS AT THE TIME OF DEATH");
 set("designation",b.designation_en||"AUTHORIZED REGISTRAR");set("authorityPerson",b.authorized_person_name||b.authorized_person_en||"");
 set("bodySign",b.name_en||"");
 const logo=(id,src)=>{const e=document.getElementById(id);if(src){e.src=src;e.style.display="block"; if(id==="formLogo")document.getElementById("formPlaceholder").style.display="none"}};
 logo("authorityLogo",b.authority_logo_url||b.state_logo_url||b.logo_url);
 logo("formLogo",b.form_logo_url);
 logo("signatureImg",b.signature_url||b.authorized_signature_url);
 const u=new URL("verify.html",location.href);u.searchParams.set("id",c.qr_verification_id);set("verifyUrl",u.href);
 new QRCode(document.getElementById("qr"),{text:u.href,width:128,height:128});
})();